### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by mattboran**
This PR adds support for Swift Package manager to this repository.

The same versions of iOS, macOS, and tvOS are supported as before, and the project structure was not changed. This means that the Carthage and CocoaPods versions of this framework still work.

I had to make 2 small changes in `ResponseDetectiveSpec.swift`:
1. Ensure `buffer` is initialized newly in the `beforeEach` block. Otherwise, running tests in a random order can fail
2. I replaced `stub(condition: isHost...` with `HTTPStubs.stubRequests`; it's possible I configured something incorrectly, but my Swift compiler was unable to find that method.

Please let me know what you think!

### CODE REVIEW

**Comment by mattboran** [comment]
@akashivskyy could you take a look a this when you get a chance?

**Comment by akashivskyy** [comment]
Thanks for your contribution, Matt! Unfortunately, I'm no longer a maintainer of this project. I'm sure @Siemian will know someone who can help you get this PR sorted. Cheers! 🙌

**Comment by Siemian** [comment]
Hi @mattboran, thank you for your contribution, i was testing your changes using Xcode 13 and unfortunately, it does not compile properly. Here is what i got:
Zrzut ekranu 2021-10-20 o 08 58 07
Could you confirm if that's working on your side? We would be happy to merge your changes.

Thanks @akashivskyy for the ping!

**Comment by mattboran** [comment]
@Siemian thanks for taking a look! It looks like I had configured the header paths incorrectly. I have added some additional build settings to the internal Objective-C target. Now, using Xcode 13.0:

- `swift test` - builds and tests pass ✅ 
- `ResponseDetective.xcodeproj` - targets still build ✅ 
- Demo app with swift package from `mattboran:feature/swiftpm`: - builds and runs ✅

Please let me know if you're seeing something different on your end! 

Edit:
I did notice that `./carthage.sh bootstrap` now fails to build `Nimble` (Xcode 13.0). This is true on the current `develop` branch as well

**Comment by mattboran** [comment]
Bumping this thread @Siemian 🙂

**Comment by Siemian** [comment]
Hi @mattboran i'm really really sorry for keep you waiting for such a long time. I checked and looks ok now, thanks for your contribution 🙇

**Comment by Siemian** [comment]
New release created: https://github.com/netguru/ResponseDetective/releases/tag/1.5.1

**Pull request merged**
